services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  db_data:


#version: '3.8'
#services:
  #db:
    #image: ankane/pgvector:latest
    #ports:
      #- "5432:5432"
    #environment:
      #POSTGRES_USER: root
      #POSTGRES_PASSWORD: password
      #POSTGRES_DB: vectordb
    #volumes:
      #- db_data:/var/lib/postgresql/data
  #restart: unless-stopped
#volumes:
  #db_data:
