services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    logging:
      driver: loki
      options:
        loki-url: "https://loki.jshingler.net/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    extra_hosts:
      - "keycloak.jshingler.net:192.168.200.85"

    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID_CLOUDFLARE}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET_CLOUDFLARE}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET_CLOUDFLARE}
    ports:
      - "4180:4180"   # Auth endpoints
      - "4181:4181"   # Metrics (optional)
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - observability
      - keycloak-network
    restart: unless-stopped

networks:
  observability:
    external: true
  keycloak-network:
    external: true

