services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    extra_hosts:
      - "jshingler.asuscomm.com:74.133.75.33"
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    ports:
      - "4180:4180"   # Auth endpoints
      - "4181:4181"   # Metrics (optional)
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - observability
    restart: unless-stopped

networks:
  observability:
    external: true

